# Generated by Django 5.1 on 2026-08-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realitionship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='realitionship.profile'),
        ),
    ]
