# Generated by Django 5.1 on 2026-08-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realitionship', '0002_anketa_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='annotation',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
