# Generated by Django 5.1 on 2026-08-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realitionship', '0003_alter_profile_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_icon',
            field=models.ImageField(blank=True, default='default_user_icon.jpg', null=True, upload_to='icons/'),
        ),
    ]
