# Generated by Django 5.1 on 2026-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realitionship', '0004_alter_profile_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
