# Generated by Django 5.2 on 2026-08-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realitionship', '0006_remove_profile_age_alter_anketa_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_marked_items',
            field=models.BooleanField(default=False),
        ),
    ]
